---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  namespace: deploy-jenkins
spec:
  selector:
    app: nodejs-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 8083
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: deploy-jenkins
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      service-deploy: service-deploy
      containers:
      - name: nodejs-app
        image: crist/app-rest:57
        ports:
          - containerPort: 8083
