---
apiVersion: v1
kind: Namespace
metadata:
  name:  deploy-jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-jenkins
  namespace: deploy-jenkins
rules:
- apiGroups: ["*"] 
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-jenkins-rolebinding
  namespace: deploy-jenkins
subjects:
- kind: User
  name: kind-kind # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-jenkins
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  namespace: deploy-jenkins
spec:
  selector:
    app: nodejs-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 8083
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: deploy-jenkins
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: crist/app-rest:$BUILD_NUMBER
        ports:
          - containerPort: 8083
